version: '3.7'

services:
  bot:
    build: .
    container_name: c6_discord_bot
    env_file: .env
    environment: 
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    expose:
      - ${NODEJS_PORT}
    volumes:
      - .:/app

networks:
  default:
    external:
      name: nginx-proxy